# Generated by Django 4.2.2 on 2023-06-28 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='caramount',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad'),
        ),
        migrations.AddField(
            model_name='car',
            name='carprice',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, null=True, verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='product',
            name='amount',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad'),
        ),
        migrations.AddField(
            model_name='product',
            name='artist',
            field=models.CharField(max_length=50, null=True, verbose_name='Artista'),
        ),
        migrations.AddField(
            model_name='product',
            name='duration',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True, verbose_name='Duracion'),
        ),
        migrations.AddField(
            model_name='product',
            name='releasedate',
            field=models.DateField(null=True, verbose_name='Fecha lanzado'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Precio'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Mensaje')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Publicado')),
                ('commentto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.product', verbose_name='Mensaje-en')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='categorie',
            field=models.ManyToManyField(default=None, null=True, to='ecommerce.genre', verbose_name='Genero'),
        ),
    ]
