# Generated by Django 4.2.2 on 2023-06-29 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_genre_car_caramount_car_carprice_product_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='car',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creacion'),
        ),
    ]
