# Generated by Django 4.2.2 on 2023-07-04 10:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_alter_car_options_car_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Comentario actualizado'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cal',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Calificacion'),
        ),
    ]
